spring:
  application:
    name: fresco

  config:
    import: optional:file:.env[.properties]

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB

  datasource:
    url: jdbc:postgresql://localhost:5433/fresco
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false

  web:
    error:
      include-message: always
      include-exception: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET:fresco-secret-key-multitenant-booking-platform-2026}
  expiration: 86400000

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://db:5433/fresco
  jpa:
    hibernate:
      ddl-auto: update
