spring:
  application:
    name: fresco

  datasource:
    url: jdbc:postgresql://localhost:5433/fresco
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: fresco-secret-key-multitenant-booking-platform-2026
  expiration: 86400000

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://db:5433/fresco
  jpa:
    hibernate:
      ddl-auto: update
